dist: xenial
language: csharp
solution: eformSDK.sln
mono: none
dotnet: 2.2.207
branches:
  only:
    - master
    - stable
    - netcore3
services:
- mysql
script:
  - dotnet restore
  - dotnet build eFormSDK.sln
  - dotnet test -v n eFormSDK.Integration.Tests/eFormSDK.Integration.Tests.csproj || travis_terminate 1;
  - dotnet test -v n eFormSDK.Tests/eFormSDK.Tests.csproj || travis_terminate 1;
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack eFormSDK.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-sdk-dotnet/eFormCore/artifacts/Microting.eForm.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
