name: .NET Core 6

on:
  push:
    branches: [ netcore6 ]
  pull_request:
    branches: [ netcore6 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [integration-tests-core-base,integration-tests-core-case,integration-tests-core-checklists,integration-tests-sqlcontroller-base,integration-tests-sqlcontroller-case,integration-tests-sqlcontroller-checklists,unit-tests-base,unit-tests-checklists,unit-tests-insight]

    steps:
    - uses: actions/checkout@v2
    - uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: 'latest'
        host port: 5672
        rabbitmq user: 'admin'
        rabbitmq password: 'password'
        rabbitmq vhost: 'vhost_name'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: ${{matrix.test}}
      run: ./${{matrix.test}}.sh
